runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "0d 30s"

handlers:

- url: /data
  static_dir: data
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /node_modules/@webcomponents/webcomponentsjs
  static_dir: webcomponentsjs
  secure: always

- url: /(.*\.js)$
  static_files: build/\1
  upload: build/.*\.js$
  secure: always

- url: /list/.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>;rel=preload;as=script,
      </src/shop-app.js>;rel=preload;as=script,
      </src/shop-list.js>;rel=preload;as=script

- url: /detail/.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>;rel=preload;as=script,
      </src/shop-app.js>;rel=preload;as=script,
      </src/shop-detail.js>;rel=preload;as=script

- url: /cart
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>;rel=preload;as=script,
      </src/shop-app.js>;rel=preload;as=script,
      </src/shop-cart.js>;rel=preload;as=script

- url: /checkout
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>;rel=preload;as=script,
      </src/shop-app.js>;rel=preload;as=script,
      </src/shop-checkout.js>;rel=preload;as=script

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link: 
      </node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js>;rel=preload;as=script,
      </src/shop-app.js>;rel=preload;as=script

skip_files:
- bundled/
- node_modules/
- src/
